-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ../extensions/ApiFeatureUsage/schema/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE api_feature_usage (
  afu_feature TEXT NOT NULL,
  afu_agent TEXT NOT NULL,
  afu_date TEXT NOT NULL,
  afu_hits INT NOT NULL,
  PRIMARY KEY(afu_date, afu_feature, afu_agent)
);
